use_frameworks!

target 'LGBUIViewController_Example' do
  pod 'LGBUIViewController', :path => '../'

  target 'LGBUIViewController_Tests' do
    pod 'LGBUIViewController', :path => '../'

    
  end
end
